name: Build & Test
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build
        shell: bash
        run: bazel build -s //:index
      - name: Cat Result
        run: cat bazel-bin/index.yaml
